// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransportationManagementSystem.Mvc.Data;

#nullable disable

namespace TransportationManagementSystem.Migrations
{
    [DbContext(typeof(TripContext))]
    [Migration("20260623142809_Update DB")]
    partial class UpdateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransportationManagementSystem.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TripId")
                        .HasColumnType("int");

                    b.HasKey("DriverId");

                    b.HasIndex("TripId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("TransportationManagementSystem.Models.Summary", b =>
                {
                    b.Property<int>("SummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SummaryId"));

                    b.Property<TimeSpan>("ActualTime")
                        .HasColumnType("time");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("End")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("In1")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("In2")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("In3")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("In4")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("Out1")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("Out2")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("Out3")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("Out4")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("Start")
                        .HasColumnType("time");

                    b.Property<int>("TripDateId")
                        .HasColumnType("int");

                    b.Property<string>("WeeklyTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SummaryId");

                    b.HasIndex("TripDateId");

                    b.HasIndex("DriverId", "TripDateId", "Start", "Out1");

                    b.ToTable("Summaries");
                });

            modelBuilder.Entity("TransportationManagementSystem.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<TimeSpan>("ActualDropoff")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("ActualPickup")
                        .HasColumnType("time");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("PickupArrival")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("ScheduledDropoff")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("ScheduledPickup")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TripActualEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TripActualStart")
                        .HasColumnType("time");

                    b.Property<int>("TripDateId")
                        .HasColumnType("int");

                    b.HasKey("TripId");

                    b.HasIndex("TripDateId");

                    b.HasIndex("DriverId", "TripDateId", "TripActualStart", "ScheduledPickup");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TransportationManagementSystem.Models.TripDate", b =>
                {
                    b.Property<int>("TripDateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripDateId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.HasKey("TripDateId");

                    b.ToTable("TripDates");
                });

            modelBuilder.Entity("TransportationManagementSystem.Models.Driver", b =>
                {
                    b.HasOne("TransportationManagementSystem.Models.Trip", null)
                        .WithMany("Drivers")
                        .HasForeignKey("TripId");
                });

            modelBuilder.Entity("TransportationManagementSystem.Models.Summary", b =>
                {
                    b.HasOne("TransportationManagementSystem.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportationManagementSystem.Models.TripDate", "TripDate")
                        .WithMany()
                        .HasForeignKey("TripDateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("TripDate");
                });

            modelBuilder.Entity("TransportationManagementSystem.Models.Trip", b =>
                {
                    b.HasOne("TransportationManagementSystem.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportationManagementSystem.Models.TripDate", "TripDate")
                        .WithMany()
                        .HasForeignKey("TripDateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("TripDate");
                });

            modelBuilder.Entity("TransportationManagementSystem.Models.Trip", b =>
                {
                    b.Navigation("Drivers");
                });
#pragma warning restore 612, 618
        }
    }
}
